# -*- coding: utf-8 -*-

# Copyright (c) 2013 by pyramid_localize authors and contributors <see AUTHORS file>
#
# This module is part of pyramid_localize and is released under
# the MIT License (MIT): http://opensource.org/licenses/MIT
localize:
    pybabel: pybabel
    locales:    # available and default locale for your app
        available: [en, de, pl]
        default: en
